config/routes.rb
Rails.application.routes.draw do
  resources :sessions, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :show, :edit, :update]
  resources :favorites, only: [:index, :create, :destroy]
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  root to: 'users#new'
  resources :pictures do
    collection do
      post :confirm
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :picture
end

app/models/picture.rb
class Picture < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user
  validates :image, presence: true
  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  has_many :pictures
  has_many :favorites, dependent: :destroy
  has_many :favorite_pictures, through: :favorites, source: :picture
  validates :name, presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 }
  before_validation { email.downcase! }
  has_secure_password
  validates :password, length: { minimum: 6 }
  mount_uploader :image, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  before_action :login_required

  private

  def login_required
    redirect_to new_session_path unless current_user
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def index
    @favorites = current_user.favorite_pictures
  end

  def create
    favorite = current_user.favorites.create(picture_id: params[:picture_id])
    redirect_to pictures_path, notice: "#{favorite.picture.user.name}さんのブログをお気に入り登録しました"
  end

  def destroy
    favorite = current_user.favorites.find_by(id: params[:id]).destroy
    redirect_to pictures_path, notice: "#{favorite.picture.user.name}さんのブログをお気に入り解除しました"
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController

  def index
    @pictures = Picture.all
  end

  def show
    @picture = Picture.find(params[:id])
    @favorite = current_user.favorites.find_by(picture_id: @picture.id)
  end

  def new
    if params[:back]
      @picture = Picture.new(picture_params)
    else
      @picture = Picture.new
    end
  end

  def create
    @picture = current_user.pictures.build(picture_params)
    if @picture.save
      PictureMailer.picture_mail(@picture).deliver
      redirect_to pictures_path, notice: '投稿しました！'
    else
      render :new
    end
  end

  def edit
    @picture = Picture.find(params[:id])
  end

  def update
    @picture = Picture.find(params[:id])
    if @picture.update(picture_params)
      redirect_to pictures_path, notice: '投稿を更新しました！'
    else
      render :edit
    end
  end

  def confirm
    @picture = current_user.pictures.build(picture_params)
      flash.now[:danger] = 'Error! Please put a picture.' if @picture.invalid?
  end

  def destroy
    @picture = Picture.find(params[:id])
    if @picture.destroy
      redirect_to pictures_path, notice: '投稿を削除しました！'
    else
      render :index
    end
  end

  private

  def picture_params
    params.require(:picture).permit(:image, :image_cache, :content)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash.now[:danger] = 'ログインに失敗しました'
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :login_required, only: [:new, :create, :edit, :update ]
  before_action :authenticate_user, only: [:show, :edit, :update ]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_path(@user.id)
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path, notice: "ユーザー情報を更新しました！"
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :image, :image_cache, :content)
  end

  def authenticate_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to new_session_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'create'
      confirm_pictures_path
    elsif action_name == 'edit'
      picture_path
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user.present?
  end 
end

app/helpers/users_helper.rb
module UsersHelper
  def user_image_url(user)
    "/user_images/#{user.image_file_name}"
  end 
end

app/views/favorites/index.html.erb
<div class="wrapper"><br><br><br><br>
  <h1><%= current_user.name %>さんのお気に入り一覧<i class="bi bi-heart-fill"></i></h1>

  <table>
    <table-head>
      <tr>
        <th>投稿者</th>
        <th>コメント</th>
        <th>画像</th>
      </tr>
    </table-head>

    <table-body>
    <% @favorites.each do |favorite| %>
      <tr>
        <td><%= favorite.user.name %></td>
        <td><%= favorite.content %></td>
        <td><%= image_tag favorite.image.url if favorite.image.present? %></td>
      </tr>
    <% end %>
    </table-body>
  </table>

  <p><%= link_to '投稿一覧に戻る', pictures_path %></p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IgClone</title>
      <%= csrf_meta_tags %>
      <%= csp_meta_tag %>

      <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
      <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
      <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
      <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
      <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
  </head>

  <body>
    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "#{key}") %>
    <% end %>

    <% if logged_in? %>
      <div class="float"><%= link_to "Profile", user_path(current_user.id) %></div>
      <div class="float"><%= link_to "Logout", session_path(current_user.id), method: :delete %></div>
    <% else %>
      <div class="float"><%= link_to "Sign up", new_user_path %></div>
      <div class="float"><%= link_to "Login", new_session_path %></div>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/pictures/_form.html.erb
<%= form_with(model: picture, local: true, url: choose_new_or_edit) do |form| %>
  <div class="field">
    <p class="mb-1 text-center"><%= form.label :image %></p>
    <p class="icon-image"><%= image_tag(picture.image.url) if picture.image && picture.image.url %></p>

    <p class="icon-image"><%= form.file_field :image %></P>
    <P><%= form.hidden_field :image_cache %></P>

    <P class="mb-1 text-center"><%= form.label :content %>
    <%= form.text_field :content %></P>
  <div>

    <P class="mb-1 text-center"><%= form.submit %></P>
<% end %>

app/views/pictures/confirm.html.erb
<div class="wrapper"><br><br><br><br>
  <h1>確認画面</h1>
  <%= form_with(model: @picture, url: pictures_path, local: true) do |form| %>

    <p><strong>画像:</strong></p>
    <p><%= image_tag(@picture.image.url) if @picture.image && @picture.image.url %></p>
    <%= form.hidden_field :image_cache %>

    <p><strong>コメント:</strong></p>
    <%= form.hidden_field :content %>
    <%= @picture.content %>

    <%= form.submit '投稿する' %>
  <% end %>

  <%= form_with(model: @picture, url: new_picture_path, local: true, method:"get") do |form| %>
    <%= form.hidden_field :image_cache %>
    <%= form.submit 'back', name: 'back' %>
  <% end %>
    <%= link_to '戻る', :back %>
</div>

app/views/pictures/edit.html.erb
<div class="wrapper">
  <h1>編集ページ</h1>

  <%= render "form", picture: @picture %>

  <br>

  <p class="btn-post"><%= link_to '投稿一覧へ戻る', pictures_path %>
</div>

app/views/pictures/index.html.erb
<div class="wrapper"><br><br><br><br>
  <h1>投稿一覧<i class="bi bi-file-earmark-richtext"></i></h1>
  <br>
  <table>
    <table-head>
      <tr>
        <th class="pt-3 pb-3 text-center">投稿者<i class="bi bi-person"></i></th>
        <th class="pt-3 pb-3 text-center">コメント<i class="bi bi-chat-text"></i></th>
        <th class="pt-3 pb-3 text-center">画像<i class="bi bi-image"></i></th>
      </tr>
    </table-head>

    <table-body>
      <% @pictures.each do |picture| %>
      <tr>
        <td class="mb-2 text-center"><%= picture.user.name %></td>
        <td class="mb-2 text-center"><%= picture.content %></td>
        <td class="pt-3 pb-3 px-5"><%= image_tag picture.image_url %></td>
        <td class="pt-3 pb-3 px-5"><%= link_to '詳細', picture_path(picture) %></td>

        <% if picture.user == current_user %>
          <td class="pt-3 pb-3 px-5"><%= link_to '編集', edit_picture_path(picture) %></td>
          <td class="pt-3 pb-3 px-5"><%= link_to '削除', picture, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% else %>
          <td></td>
          <td></td>
        <% end %>
      </tr>
      <% end %>
    </table-body>
  </table>
  <button type ="button" class="btn btn-link"><%= link_to '新規投稿ページへ', new_picture_path %></button>
</div>

app/views/pictures/new.html.erb
<div class="wrapper"><br><br><br><br>
  <h1>新規投稿</h1>

  <%= render "form", picture: @picture %>

  <br>

  <p class="text-center"><% link_to '投稿一覧へ戻る', pictures_path %></p>
</div>

app/views/pictures/show.html.erb
<div class="wrapper"><br><br><br><br>
  <h1>詳細ページ</h1><br>

  <div class="show">
  <p>
    <strong>Image:</strong>
    <%= image_tag @picture.image.url %>
  </p>

  <P>
    <strong>コメント:</strong>
    <%= @picture.content %>
  </P>
  </div>
  <% unless @picture.user_id == current_user.id %>
    <% if @favorite.present? %>
    <button type="button" class="btn btn-outline-danger">
      <%= link_to 'unlike', favorite_path(id: @favorite.id), method: :delete %>
      <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-heartbreak-fill" viewBox="0 0 16 16">
        <path fill-rule="evenodd" d="M8.931.586 7 3l1.5 4-2 3L8 15C22.534 5.396 13.757-2.21 8.931.586ZM7.358.77 5.5 3 7 7l-1.5 3 1.815 4.537C-6.533 4.96 2.685-2.467 7.358.77Z"></path>
      </svg>
    </button>

    <% else %>

     <button type="button" class="btn btn-outline-danger"><%= link_to 'Like', favorites_path(picture_id: @picture.id), method: :post %>
       <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-heart-fill" viewBox="0 0 16 16">
         <path fill-rule="evenodd" d="M8 1.314C12.438-3.248 23.534 4.735 8 15-7.534 4.736 3.562-3.248 8 1.314z"></path>
       </svg>
      </button>
    <% end %>
  <% end %>

  <%= link_to '投稿一覧に戻る', pictures_path %>
    <% if @picture.user == current_user %>
      <%= link_to '編集', edit_picture_path(@picture) %>
    <% end %>
  </div>

app/views/users/edit.html.erb
<div class="wrapper"><br><br><br><br>
  <h1>ユーザー情報の編集</h1>

  <%= form_with(model: @user, local: true) do |f| %>

    <% if @user.errors.any? %>
      <div id="error_explanation">
        <h2><%= @user.errors.count %>件のエラーがあります。</h2>
        <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

      <p class="mb-2"><%= f.label :name %></p>
      <P><%= f.text_field :name, class:"w-25" %></P>

      <p class="mb-2"><%= f.label :email %></P>
      <p><%= f.email_field :email, class:"w-25" %></p>

      <P class="mb-2"><%= f.label :プロフィール画像 %></P>
      <%= image_tag(@user.image.url) if @user.image && @user.image.url %>
      <p class="icon-image"><%= f.file_field :image, class:"w-100" %></p>

      <P class="mb-2"><%= f.label :password %></P>
      <P><%= f.password_field :password, class:"w-25" %></P>

      <P class="mb-2"><%= f.label :password_confirmation %></P>
      <P><%= f.password_field :password_confirmation, class:"w-25" %></P>

      <%= f.submit "更新する" %>
    <% end %>

    <br><br><br>
    <p><%= link_to '前のページに戻る', user_path %></p>
    <p><%= link_to '投稿一覧画面へ戻る', pictures_path %></p>
  </div>

app/views/users/new.html.erb
<%= form_with(model: @user, local: true) do |f| %>
<div class ="container">
  <div class="wrapper">
    <h1>Sign up</h1>

    <% if @user.errors.any? %>
      <div id="error_explanation">
        <h2><%= @user.errors.count %>件のエラーがあります。</h2>
        <ul>
        <%= @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <form action ="" method="post" name="Login_Form" class="form-signin">
      <h3 class="form-signin-heading">Welcome!! Please sign in!</h3>
        <hr clas="colorgragh"><br>

          <p class="mb-2"><%= f.label :name %></p>
          <P><%= f.text_field :name, class:"w-25" %></P>

          <p class="mb-2"><%= f.label :email %></P>
          <p><%= f.email_field :email, class:"w-25" %></p>

          <P class="mb-2"><%= f.label :プロフィール画像 %></P>
          <p class="icon-image"><%= f.file_field :image, class:"w-100" %></p>

          <P class="mb-2"><%= f.label :password %></P>
          <P><%= f.password_field :password, class:"w-25" %></P>

          <P class="mb-2"><%= f.label :password_confirmation %></P>
          <P><%= f.password_field :password_confirmation, class:"w-25" %></P>
          <br>

          <button class="btn btn-lg btn-primary btn-block" name="Submit" value="Login" type="Submit">Create my account</button>
    </form>
  </div>
</div>
<% end %>

app/views/users/show.html.erb
<div calss="wrapper">
  <div class="clearfix"><br><br><br>
    <h1 class="mb-2 text-center">Welcome to <%= @user.name %>'s page  <i class="bi bi-person-circle"></i></h1>
    <p class="text-center"><i class="bi bi-heart-fill"><%= link_to 'お気に入り一覧へ', favorites_path %></i></p>

    <p class="mb-2 text-center"><i class="bi bi-envelope-fill"></i>メールアドレス:<%= @user.email %></p>
    <p class="mb-2 text-center"><strong>画像:</strong>
    <p class="mb-2 text-center"><%= image_tag @user.image.url, class: "rounded-circle", size: "150*150" if @user.image && @user.image.url %></p>
    <br>
    <p class="mb-2 text-center"><%= link_to '編集', edit_user_path(@user.id), class:"btn btn-info" %></p>

    <br><br><br>
    <p class="mb-3 text-center"><%= link_to '新規投稿を作成', new_picture_path, class:"btn btn-info" %></p>
    <p class="mb-3 text-center"><%= link_to '投稿一覧へ', pictures_path, class:"btn btn-info" %></p>
  </div?
</div>